name: expense_tracker
description: A personal expense tracker.
publish_to: 'none'
version: 1.6.0+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Database
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.9.0

  shared_preferences: ^2.3.2

  file_picker: ^8.0.0

  # State
  provider: ^6.1.1

  # Charts
  fl_chart: ^0.67.0

  # CSV + XLSX + sharing
  csv: ^6.0.0
  excel: ^4.0.6
  share_plus: ^7.2.2

  # Utilities
  intl: any
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true